name: HomeDB
description: HomeDB Home Assistant Add-on
slug: home_db
url: https://github.com/benbur98/HomeDB
version: "1.0.0"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
