name: HomeDB
description: HomeDB - A Database for the Home
slug: home_db
url: https://github.com/benbur98/HomeDB
version: "1.0.0"
startup: application
boot: auto
ingress: true
panel_icon: mdi:home-silo
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8099
ports_description:
  8000/tcp: Frontend UI Port
