name: HomeDB
description: HomeDB - A Database for the Home
slug: home_db
url: https://github.com/ben-burwood/HomeDB
version: 1.0.01
startup: application
boot: auto
ingress: true
panel_icon: mdi:home-silo
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
